dist: xenial
language: java
addons:
  apt:
    packages:
      - ant

before_install: 
    - cd spring-apiRest/
    
script:
    - ./mvnw test -B

after_success:
  - bash <(curl -s https://codecov.io/bash)
