dist: bionic
addons:
  apt:
    sources:
      - ppa:chris-lea/redis-server
    packages:
    - redis-tools
    - redis-server

language: java

jdk:
  - openjdk8

addons:
  apt:
    packages:
      - ant
